---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forensic-logging-sidecar-config
  labels:
      app: forensic-logging-sidecar
data:
  ## The name for the sidecar service. Default: TestService
  # sidecar.name: "TestService"
  ## The port the sidecar server will run on. Default: 5678
  sidecar.port: "5678"
  ## The message batch size. Default: 64
  # sidecar.batch.side: 64
  # The url for the KMS. Default: ws://localhost:8080/sidecar
  kms.uri: "ws://central-kms:80/sidecar"
  ## The time, in milliseconds, between pings to the KMS. Default: 30000
  # kms.ping.interval: 30000
  ## The time, in milliseconds, to timeout a request to the KMS. Default: 30000
  # kms.request.timeout: 30000
  ## The time, in milliseconds, to timeout a connection attempt to the KMS. Default: 60000
  # kms.connect.timeout: 60000
  ## TBC?
  # kms.reconnect.interval: 
